### ISSUE TITLE
[Help needed] Running Eclipse Kura on Concierge -  ClassLoader.getPackage() returns null

### ISSUE THREAD

**Issue by svilenvul** [eclipse/concierge#48]
Hello, 
I ran the Concierge runtime and I have great impressions from the startup time of the framework, I really appreciate your efforts on the project !

I have already started most of the Eclipse Kura bundles in the runtime and everything looked good until I faced a strange issue. I saw that @JochenHiller already [made some tests running Kura](https://github.com/JochenHiller/concierge-tests), so maybe you can help me to understand the cause a little bit better.

The setup that I have is:

```
# Concierge services
-istart ${concierge.dir}/org.eclipse.concierge.service.packageadmin-${concierge.version}*.jar
-istart ${concierge.dir}/org.eclipse.concierge.service.startlevel-${concierge.version}*.jar
-istart ${concierge.dir}/org.eclipse.concierge.service.xmlparser-${concierge.version}*.jar

# OSGi Services
....
# Dependencies
...
# Start Kura Core bundles
-istart ${system.dir}/org.eclipse.kura.api-*.jar

-install ${system.dir}/org.eclipse.kura.localization.resources-*.jar  //This is a fragment bundle
-istart ${system.dir}/org.eclipse.kura.localization-*.jar                   //This is a host bundle

....
-istart ${system.dir}/org.eclipse.kura.wire.helper.provider-*.jar     //This is the caller who calls the host bundle 

```

The situation is the following - while `org.eclipse.kura.internal.wire.helper.WireHelperServiceImpl` is being registered the following exception is being logged on the console.

[error-message.txt](https://github.com/eclipse/concierge/files/1667334/error-message.txt)

I have attached a remote debugger and traced the cause of the `NullPointerException` that you see in the log above to a `ClassLoader.getPackage(String name)` returning null for a package in the fragment bundle.

I tried several things with different start levels, but I did not get far with them.

I feel a bit lost what can I do further, could you please give me some hints ?

**Comment by JochenHiller** [comment]
@svilenvul, thanks for reporting that issue, and your analysis about root cause.

Can you share your running environment (send me a personal message)?
I would like to see the host/fragment bundles with their export-packages. And might need to debug into the framework to understand why it will return a null on requested Java package. This scenario is a little more complex as the class asking for package is from a jar file from Bundle-Classpath, which is handled differently in framework.

The time when I did get Kura running on Concierge, these kind of bundles were not yet part of distribution. So it seems to be a new issues raising up now.

**Comment by amitjoy** [comment]
@JochenHiller @svilenvul These are bundles that I introduced for Kura Wires. According to the log, the problem is apparently in `com.github.rodionmoiseev.c10n` library used by locallization bundle in Kura. And localization bundle is primarily used by all the bundles in Kura Wires (but not Kura completely). hence there exists a chain of errors caused by the problem in `com.github.rodionmoiseev.c10n`. Every class that provides localization transitively depends on `com.github.rodionmoiseev.c10n` through dynamic proxy. And somehow `com.github.rodionmoiseev.c10n` cannot access the class instance properly.

**Comment by JochenHiller** [comment]
@amitjoy Yes, indeed this seems to be the problem.
As @svilenvul pointed out it might be indeed a bug in the framework in the given specific use case with fragments and use Bundle-Classpath.

**Comment by JochenHiller** [comment]
I found the root cause of the problem doing debugging on the scenario: it is indeed a problem in BundleClassLoader in case of a fragment:

The code at https://github.com/eclipse/concierge/blob/master/framework/org.eclipse.concierge/src/org/eclipse/concierge/BundleImpl.java#L3098 is missing a 'definePackage(packageOf(classname))`

I fixed it for testing purposes and Concierge/Kura does startup then without any issues.

I will provide a PR to fix that problem

**Comment by JochenHiller** [comment]
@svilenvul You can get the latest SNAPSHOT build from https://ci.eclipse.org/concierge/job/R5.1_nightly/78/ and use it for further testing

**Comment by svilenvul** [comment]
Many thanks @JochenHiller !
